name: CI
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
  packages: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v2
      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ hashFiles('**/pyproject.toml','**/uv.lock*') }}
      - run: uv sync --frozen
      - name: Lint & type-check
        run: |
          ruff check .
          mypy src
      - name: Unit tests
        env:
          USE_MOCK_GPIO: "1"
        run: |
          pytest -m "not integration and not hardware" --cov=your_pkg --cov-report=xml
      - uses: codecov/codecov-action@v5  # optional
        if: always()

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push multi-arch
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/arm64,linux/arm/v7
          tags: |
            ghcr.io/${{ github.repository }}/app:sha-${{ github.sha }}
            ghcr.io/${{ github.repository }}/app:latest
