name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install package and test deps
        run: |
          python -m pip install --upgrade pip
          pip install -e . pytest
      - name: Run tests
        run: pytest -q
      - name: Run CLI (simulate)
        run: python -m pumpkin_pi --simulate --count 2 --interval 0.1

